version: '3.9'

# Services
services:
  app:
    build: ./python/
    depends_on:
      - mysql

  mysql:
    build: ./DB/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'chatRMI'
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
