-- MySQL Script generated by MySQL Workbench
-- sex 02 dez 2022 17:32:35
-- Model: chatRMI Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chatRMI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatRMI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatRMI` ;
USE `chatRMI` ;

-- -----------------------------------------------------
-- Table `chatRMI`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_user` (
  `id` INT UNSIGNED NOT NULL,
  `address_ip` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatRMI`.`tb_user_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_user_request` (
  `tb_user_request` INT NOT NULL,
  `tb_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tb_user_request`, `tb_user_id`),
  INDEX `fk_tb_user_request_tb_user1_idx` (`tb_user_id` ASC),
  CONSTRAINT `fk_tb_user_request_tb_user1`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `chatRMI`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatRMI`.`tb_user_receive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_user_receive` (
  `tb_user_receive` INT NOT NULL,
  `tb_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tb_user_receive`, `tb_user_id`),
  INDEX `fk_tb_user_receive_tb_user1_idx` (`tb_user_id` ASC),
  CONSTRAINT `fk_tb_user_receive_tb_user1`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `chatRMI`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatRMI`.`tb_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_messages` (
  `id` INT UNSIGNED NOT NULL,
  `timeMessageSend` VARCHAR(45) NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  `file` VARCHAR(45) NOT NULL,
  `tb_user_request_tb_user_request` INT NOT NULL,
  `tb_user_request_tb_user_id` INT UNSIGNED NOT NULL,
  `tb_user_receive_tb_user_receive` INT NOT NULL,
  `tb_user_receive_tb_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tb_user_request_tb_user_request`, `tb_user_request_tb_user_id`, `tb_user_receive_tb_user_receive`, `tb_user_receive_tb_user_id`),
  INDEX `fk_tb_messages_tb_user_request1_idx` (`tb_user_request_tb_user_request` ASC, `tb_user_request_tb_user_id` ASC),
  INDEX `fk_tb_messages_tb_user_receive1_idx` (`tb_user_receive_tb_user_receive` ASC, `tb_user_receive_tb_user_id` ASC),
  CONSTRAINT `fk_tb_messages_tb_user_request1`
    FOREIGN KEY (`tb_user_request_tb_user_request` , `tb_user_request_tb_user_id`)
    REFERENCES `chatRMI`.`tb_user_request` (`tb_user_request` , `tb_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_messages_tb_user_receive1`
    FOREIGN KEY (`tb_user_receive_tb_user_receive` , `tb_user_receive_tb_user_id`)
    REFERENCES `chatRMI`.`tb_user_receive` (`tb_user_receive` , `tb_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatRMI`.`tb_privateChat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_privateChat` (
  `id` INT UNSIGNED NOT NULL,
  `address_ip` VARCHAR(45) NOT NULL,
  `tb_messages_id` INT UNSIGNED NOT NULL,
  `tb_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tb_messages_id`, `tb_user_id`),
  INDEX `fk_tb_privateChat_tb_messages1_idx` (`tb_messages_id` ASC),
  INDEX `fk_tb_privateChat_tb_user1_idx` (`tb_user_id` ASC),
  CONSTRAINT `fk_tb_privateChat_tb_messages1`
    FOREIGN KEY (`tb_messages_id`)
    REFERENCES `chatRMI`.`tb_messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_privateChat_tb_user1`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `chatRMI`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatRMI`.`tb_userAdmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_userAdmin` (
  `id` INT UNSIGNED NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  `tb_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tb_user_id`),
  INDEX `fk_tb_userAdmin_tb_user1_idx` (`tb_user_id` ASC),
  CONSTRAINT `fk_tb_userAdmin_tb_user1`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `chatRMI`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatRMI`.`tb_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatRMI`.`tb_group` (
  `id` INT UNSIGNED NOT NULL,
  `address_ip` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `tb_messages_id` INT UNSIGNED NOT NULL,
  `tb_privateChat_id` INT UNSIGNED NOT NULL,
  `tb_privateChat_tb_messages_id` INT UNSIGNED NOT NULL,
  `tb_privateChat_tb_user_id` INT UNSIGNED NOT NULL,
  `tb_userAdmin_id` INT UNSIGNED NOT NULL,
  `tb_userAdmin_tb_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tb_messages_id`, `tb_privateChat_id`, `tb_privateChat_tb_messages_id`, `tb_privateChat_tb_user_id`, `tb_userAdmin_id`, `tb_userAdmin_tb_user_id`),
  INDEX `fk_tb_user_tb_messages1_idx` (`tb_messages_id` ASC),
  INDEX `fk_tb_group_tb_privateChat1_idx` (`tb_privateChat_id` ASC, `tb_privateChat_tb_messages_id` ASC, `tb_privateChat_tb_user_id` ASC),
  INDEX `fk_tb_group_tb_userAdmin1_idx` (`tb_userAdmin_id` ASC, `tb_userAdmin_tb_user_id` ASC),
  CONSTRAINT `fk_tb_user_tb_messages1`
    FOREIGN KEY (`tb_messages_id`)
    REFERENCES `chatRMI`.`tb_messages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_group_tb_privateChat1`
    FOREIGN KEY (`tb_privateChat_id` , `tb_privateChat_tb_messages_id` , `tb_privateChat_tb_user_id`)
    REFERENCES `chatRMI`.`tb_privateChat` (`id` , `tb_messages_id` , `tb_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_group_tb_userAdmin1`
    FOREIGN KEY (`tb_userAdmin_id` , `tb_userAdmin_tb_user_id`)
    REFERENCES `chatRMI`.`tb_userAdmin` (`id` , `tb_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SET NAMES utf8mb4;

INSERT INTO `tb_user` (`id`, `address_ip`, `name`, `image`, `password`) VALUES
(1,	'192.168.10.1',	'Gustavo Silva Quieregato',	'assets/images01.png',	'vgpwgv32');